import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  const property = await prisma.property.create({
    data: {
      name: "Sukhumvit Residence",
      address: "Bangkok, Thailand"
    }
  });

  const rooms = await prisma.$transaction(
    ["101", "102", "103", "104"].map((roomNumber) =>
      prisma.room.create({
        data: {
          propertyId: property.id,
          roomNumber,
          status: roomNumber === "104" ? "VACANT" : "OCCUPIED",
          monthlyRent: 8500
        }
      })
    )
  );

  const tenantA = await prisma.tenant.create({
    data: {
      fullName: "Anan Boonmee",
      phone: "0811112222"
    }
  });

  const tenantB = await prisma.tenant.create({
    data: {
      fullName: "Nicha Ploy",
      phone: "0823334444"
    }
  });

  const activeLeaseA = await prisma.leaseContract.create({
    data: {
      roomId: rooms[0].id,
      tenantId: tenantA.id,
      startDate: new Date("2026-01-01"),
      endDate: new Date("2026-12-31"),
      monthlyRent: 8500,
      securityAmount: 8500,
      status: "ACTIVE"
    }
  });

  const activeLeaseB = await prisma.leaseContract.create({
    data: {
      roomId: rooms[1].id,
      tenantId: tenantB.id,
      startDate: new Date("2026-02-01"),
      endDate: new Date("2027-01-31"),
      monthlyRent: 8500,
      securityAmount: 8500,
      status: "ACTIVE"
    }
  });

  await prisma.room.update({
    where: { id: rooms[0].id },
    data: { currentTenantName: tenantA.fullName }
  });
  await prisma.room.update({
    where: { id: rooms[1].id },
    data: { currentTenantName: tenantB.fullName }
  });

  await prisma.rentInvoice.createMany({
    data: [
      {
        roomId: rooms[0].id,
        tenantId: tenantA.id,
        billingYear: 2026,
        billingMonth: 4,
        dueDate: new Date("2026-04-05"),
        amount: 8500,
        status: "PAID",
        paidAt: new Date("2026-04-03")
      },
      {
        roomId: rooms[1].id,
        tenantId: tenantB.id,
        billingYear: 2026,
        billingMonth: 4,
        dueDate: new Date("2026-04-05"),
        amount: 8500,
        status: "OVERDUE"
      }
    ]
  });

  const invoiceA = await prisma.rentInvoice.findFirstOrThrow({
    where: { tenantId: tenantA.id, billingMonth: 4, billingYear: 2026 }
  });

  await prisma.paymentTransaction.create({
    data: {
      rentInvoiceId: invoiceA.id,
      paidAmount: 8500,
      paidAt: new Date("2026-04-03"),
      method: "BANK_TRANSFER",
      referenceNo: "TRX-APR-001"
    }
  });

  await prisma.expenseRecord.createMany({
    data: [
      {
        roomId: rooms[0].id,
        type: "WATER",
        title: "Water bill Room 101",
        amount: 350,
        expenseDate: new Date("2026-04-10")
      },
      {
        roomId: rooms[1].id,
        type: "ELECTRICITY",
        title: "Electricity bill Room 102",
        amount: 1200,
        expenseDate: new Date("2026-04-10")
      },
      {
        type: "FIXED",
        title: "Mortgage payment",
        amount: 15000,
        expenseDate: new Date("2026-04-01")
      }
    ]
  });

  await prisma.calendarEvent.createMany({
    data: [
      {
        roomId: rooms[1].id,
        title: "Rent due - Room 102",
        eventType: "RENT_DUE",
        eventDate: new Date("2026-05-05"),
        status: "OVERDUE"
      },
      {
        roomId: rooms[0].id,
        title: "Lease expiry - Room 101",
        eventType: "LEASE_EXPIRY",
        eventDate: new Date("2026-12-31"),
        status: "UPCOMING"
      }
    ]
  });

  await prisma.reportSnapshot.create({
    data: {
      propertyId: property.id,
      year: 2026,
      month: 4,
      totalIncome: 8500,
      totalExpense: 16550,
      occupancyRate: 75,
      payload: {
        notes: "Generated by seed data",
        leases: [activeLeaseA.id, activeLeaseB.id]
      }
    }
  });
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    // Keep failure explicit for CI and local debugging.
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
